'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'
'     このファイルへの変更は、正しくない動作の原因となる場合があります。
'     コードが再生成されます。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' SuccessMessagePlaceHolder コントロール。
    ''' </summary>
    ''' <remarks>
    ''' 自動生成されたフィールド。
    ''' 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' ChangePassword コントロール。
    ''' </summary>
    ''' <remarks>
    ''' 自動生成されたフィールド。
    ''' 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' CreatePassword コントロール。
    ''' </summary>
    ''' <remarks>
    ''' 自動生成されたフィールド。
    ''' 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' PhoneNumber コントロール。
    ''' </summary>
    ''' <remarks>
    ''' 自動生成されたフィールド。
    ''' 変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.Label
    
End Class
