'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'
'     このファイルへの変更は、正しくない動作の原因となる場合があります。
'     コードが再生成されます。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegisterExternalLogin

    '''<summary>
    '''電子メール コントロール。
    '''</summary>
    '''<remarks>
    '''自動生成されたフィールド。
    '''変更するには、フィールドの宣言をデザイナー ファイルから分離コード ファイルに移動します。
    '''</remarks>
    Protected WithEvents email As Global.System.Web.UI.WebControls.TextBox
End Class
