CREATE TABLE IF NOT EXISTS TICKET( 
  TICKET_ID MEDIUMINT PRIMARY KEY AUTO_INCREMENT
  , EVENT_ID MEDIUMINT NOT NULL
  , RANK_ID MEDIUMINT NOT NULL
  , NAME VARCHAR (255) NOT NULL
  , FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
  , FOREIGN KEY (RANK_ID) REFERENCES RANK(RANK_ID)
); 



