CREATE TABLE IF NOT EXISTS RANK( 
  RANK_ID MEDIUMINT PRIMARY KEY AUTO_INCREMENT
  , NAME VARCHAR (255) NOT NULL
  , PRICE MEDIUMINT NOT NULL
  , EVENT_ID MEDIUMINT NOT NULL
  , FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
); 

