
Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest") then
    # Guest Additions自動更新の無効化設定
    #config.vbguest.auto_update = false
  end

  if Vagrant.has_plugin?("vagrant-cachier") then
    config.cache.scope = :box
  end

  config.vm.box = "centos7_2"
  #共有フォルダ
  config.vm.synced_folder "share/", "/vagrant"

  # 1台目の設定 (webサーバー)
  config.vm.define "vm1" do |server|
    server.vm.network "private_network", ip: "192.168.33.20"

    # VirtualBoxのGUI上の名前 (デフォルトだと長い名前になるので)
    server.vm.provider "virtualbox" do |vb|
      vb.name = "postgresql-server-v2"
      vb.customize ["modifyvm", :id, "--memory", 2048]
    end

    # vagrant destroy実行時に"playbookが無い"と言われてしまうので
    # vagrant up, vagrant provision実行時のみ通るようにする
    if ARGV[0] == "up" || ARGV[0] == "provision" then
      server.vm.provision "ansible_local" do |ansible|
        ansible.inventory_path = "./hosts/hosts"
        ansible.playbook       = "./playbook.yml"
        ansible.limit          = "redmine-servers"
      end
    end
  end

end
