Vagrant.configure(2) do |config|
  config.vm.define :nodeJS do |node|
    node.vm.box = "centos7"
    node.vm.network :forwarded_port, guest: 22, host: 2030, id: "ssh"
    node.vm.network :private_network, ip: "192.168.33.30"
  end
end
